// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: project

#include "../ui.h"

void ui_historylist_screen_init(void)
{
    ui_historylist = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_historylist, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_historylist, &ui_img_1062747148, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_list = lv_obj_create(ui_historylist);
    lv_obj_remove_style_all(ui_list);
    lv_obj_set_width(ui_list, 582);
    lv_obj_set_height(ui_list, 309);
    lv_obj_set_x(ui_list, -8);
    lv_obj_set_y(ui_list, -40);
    lv_obj_set_align(ui_list, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_list, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_list, lv_color_hex(0x96CF9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_list, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_templateitem2 = lv_obj_create(ui_list);
    lv_obj_remove_style_all(ui_templateitem2);
    lv_obj_set_width(ui_templateitem2, 493);
    lv_obj_set_height(ui_templateitem2, 381);
    lv_obj_set_x(ui_templateitem2, -5);
    lv_obj_set_y(ui_templateitem2, 15);
    lv_obj_set_align(ui_templateitem2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_templateitem2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_templateitem2, lv_color_hex(0x8DC19E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_templateitem2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_templateitem2);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day, -195);
    lv_obj_set_y(ui_day, -100);
    lv_obj_set_align(ui_day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day, "日期");
    lv_obj_set_style_text_font(ui_day, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_num2 = lv_label_create(ui_templateitem2);
    lv_obj_set_width(ui_num2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_num2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_num2, 36);
    lv_obj_set_y(ui_num2, -103);
    lv_obj_set_align(ui_num2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_num2, "数量");
    lv_obj_set_style_text_font(ui_num2, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_total = lv_label_create(ui_templateitem2);
    lv_obj_set_width(ui_total, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_total, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_total, 152);
    lv_obj_set_y(ui_total, -99);
    lv_obj_set_align(ui_total, LV_ALIGN_CENTER);
    lv_label_set_text(ui_total, "总价");
    lv_obj_set_style_text_font(ui_total, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digtal = lv_label_create(ui_templateitem2);
    lv_obj_set_width(ui_digtal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digtal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digtal, -81);
    lv_obj_set_y(ui_digtal, -100);
    lv_obj_set_align(ui_digtal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digtal, "订单号");
    lv_obj_set_style_text_font(ui_digtal, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnscreencart = lv_btn_create(ui_historylist);
    lv_obj_set_width(ui_returnscreencart, 262);
    lv_obj_set_height(ui_returnscreencart, 58);
    lv_obj_set_x(ui_returnscreencart, 242);
    lv_obj_set_y(ui_returnscreencart, 189);
    lv_obj_set_align(ui_returnscreencart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_returnscreencart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_returnscreencart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_returnscreencart, lv_color_hex(0x81B98A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_returnscreencart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_returnscreencart);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "继续选购");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_returnscreencart, ui_event_returnscreencart, LV_EVENT_ALL, NULL);

}
