// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: project

#include "../ui.h"

void ui_sign_up_screen_init(void)
{
    ui_sign_up = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_sign_up, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_sign_up, &ui_img_1062747148, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_usrname2 = lv_textarea_create(ui_sign_up);
    lv_obj_set_width(ui_usrname2, 366);
    lv_obj_set_height(ui_usrname2, 62);
    lv_obj_set_x(ui_usrname2, -18);
    lv_obj_set_y(ui_usrname2, -169);
    lv_obj_set_align(ui_usrname2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_usrname2, "username");



    ui_usrname3 = lv_textarea_create(ui_sign_up);
    lv_obj_set_width(ui_usrname3, 366);
    lv_obj_set_height(ui_usrname3, 62);
    lv_obj_set_x(ui_usrname3, -20);
    lv_obj_set_y(ui_usrname3, -62);
    lv_obj_set_align(ui_usrname3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_usrname3, "same username");



    ui_Keyboard2 = lv_keyboard_create(ui_sign_up);
    lv_obj_set_width(ui_Keyboard2, 782);
    lv_obj_set_height(ui_Keyboard2, 170);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 145);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_returnlogin = lv_btn_create(ui_sign_up);
    lv_obj_set_width(ui_returnlogin, 198);
    lv_obj_set_height(ui_returnlogin, 55);
    lv_obj_set_x(ui_returnlogin, 139);
    lv_obj_set_y(ui_returnlogin, 25);
    lv_obj_set_align(ui_returnlogin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_returnlogin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_returnlogin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_returnlogin, lv_color_hex(0x85C28D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_returnlogin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_returnlogin);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "返回登录界面");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnlogin2 = lv_btn_create(ui_sign_up);
    lv_obj_set_width(ui_returnlogin2, 198);
    lv_obj_set_height(ui_returnlogin2, 59);
    lv_obj_set_x(ui_returnlogin2, -161);
    lv_obj_set_y(ui_returnlogin2, 24);
    lv_obj_set_align(ui_returnlogin2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_returnlogin2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_returnlogin2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_returnlogin2, lv_color_hex(0x85C28D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_returnlogin2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_returnlogin2);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "确认注册");
    lv_obj_set_style_text_font(ui_Label44, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_usrname2, ui_event_usrname2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_usrname3, ui_event_usrname3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_returnlogin, ui_event_returnlogin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_returnlogin2, ui_event_returnlogin2, LV_EVENT_ALL, NULL);

}
