// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: project

#include "../ui.h"

void ui_ScreenPay_screen_init(void)
{
    ui_ScreenPay = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenPay, &ui_img_1062747148, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_ScreenPay);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 784);
    lv_obj_set_height(ui_Container7, 89);
    lv_obj_set_x(ui_Container7, -1);
    lv_obj_set_y(ui_Container7, -185);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 2);
    lv_obj_set_y(ui_Label28, -13);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "订单支付");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_heiti301, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea9 = lv_textarea_create(ui_Container7);
    lv_obj_set_width(ui_TextArea9, 158);
    lv_obj_set_height(ui_TextArea9, 51);
    lv_obj_set_x(ui_TextArea9, -281);
    lv_obj_set_y(ui_TextArea9, -19);
    lv_obj_set_align(ui_TextArea9, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea9, "返回结算");
    lv_textarea_set_placeholder_text(ui_TextArea9, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextArea9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea9, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea9, lv_color_hex(0x77BB88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_shouldpay = lv_textarea_create(ui_ScreenPay);
    lv_obj_set_width(ui_shouldpay, 340);
    lv_obj_set_height(ui_shouldpay, 66);
    lv_obj_set_x(ui_shouldpay, 6);
    lv_obj_set_y(ui_shouldpay, -129);
    lv_obj_set_align(ui_shouldpay, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_shouldpay, "应付:36元");
    lv_textarea_set_placeholder_text(ui_shouldpay, "Placeholder...");
    lv_obj_set_style_text_align(ui_shouldpay, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shouldpay, &ui_font_chinese36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_shouldpay, lv_color_hex(0x77BB88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shouldpay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label29 = lv_label_create(ui_ScreenPay);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 10);
    lv_obj_set_y(ui_Label29, -63);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "请扫码支付");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image20 = lv_img_create(ui_ScreenPay);
    lv_img_set_src(ui_Image20, &ui_img_ewm_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 188
    lv_obj_set_x(ui_Image20, 11);
    lv_obj_set_y(ui_Image20, 58);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_surepay = lv_btn_create(ui_ScreenPay);
    lv_obj_set_width(ui_surepay, 166);
    lv_obj_set_height(ui_surepay, 46);
    lv_obj_set_x(ui_surepay, -190);
    lv_obj_set_y(ui_surepay, 194);
    lv_obj_set_align(ui_surepay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_surepay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_surepay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_surepay, lv_color_hex(0x77BB88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_surepay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_surepay);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "已确认支付");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelpay = lv_btn_create(ui_ScreenPay);
    lv_obj_set_width(ui_cancelpay, 154);
    lv_obj_set_height(ui_cancelpay, 50);
    lv_obj_set_x(ui_cancelpay, 172);
    lv_obj_set_y(ui_cancelpay, 194);
    lv_obj_set_align(ui_cancelpay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cancelpay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_cancelpay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cancelpay, lv_color_hex(0x77BB88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cancelpay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_cancelpay);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "取消订单");
    lv_obj_set_style_text_font(ui_Label40, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextArea9, ui_event_TextArea9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_surepay, ui_event_surepay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cancelpay, ui_event_cancelpay, LV_EVENT_ALL, NULL);

}
