// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: project

#include "../ui.h"

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenMain, &ui_img_1062747148, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnentershop = lv_btn_create(ui_ScreenMain);
    lv_obj_set_width(ui_btnentershop, 353);
    lv_obj_set_height(ui_btnentershop, 99);
    lv_obj_set_x(ui_btnentershop, 174);
    lv_obj_set_y(ui_btnentershop, 54);
    lv_obj_set_align(ui_btnentershop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnentershop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnentershop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnentershop, lv_color_hex(0x78B880), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnentershop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_btnentershop);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 6);
    lv_obj_set_y(ui_Label2, 2);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "进入购物");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_chinese36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 166);
    lv_obj_set_y(ui_Label3, 124);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "即买即取-扫码支付-自动出货");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x409A70), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_chinse16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeltitle = lv_textarea_create(ui_ScreenMain);
    lv_obj_set_width(ui_labeltitle, 188);
    lv_obj_set_height(ui_labeltitle, 50);
    lv_obj_set_x(ui_labeltitle, -275);
    lv_obj_set_y(ui_labeltitle, -189);
    lv_obj_set_align(ui_labeltitle, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_labeltitle, "自助贩卖机");
    lv_textarea_set_placeholder_text(ui_labeltitle, "Placeholder...");
    lv_obj_set_style_text_color(ui_labeltitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeltitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labeltitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltitle, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_labeltitle, lv_color_hex(0x78B880), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_labeltitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label5 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 306);
    lv_obj_set_y(ui_Label5, 210);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "客服电话  88888888");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x3D6048), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_chinese162, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image6, &ui_img_435601465);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 250
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 221
    lv_obj_set_x(ui_Image6, -196);
    lv_obj_set_y(ui_Image6, 10);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Image6, lv_color_hex(0x65A973), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Image6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelservicetip1 = lv_textarea_create(ui_ScreenMain);
    lv_obj_set_width(ui_labelservicetip1, 216);
    lv_obj_set_height(ui_labelservicetip1, 46);
    lv_obj_set_x(ui_labelservicetip1, 166);
    lv_obj_set_y(ui_labelservicetip1, -99);
    lv_obj_set_align(ui_labelservicetip1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_labelservicetip1, "24小时自助服务");
    lv_textarea_set_placeholder_text(ui_labelservicetip1, "Placeholder...");
    lv_obj_set_style_text_color(ui_labelservicetip1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelservicetip1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelservicetip1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelservicetip1, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_labelservicetip1, lv_color_hex(0x78B880), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_labelservicetip1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label7 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 173);
    lv_obj_set_y(ui_Label7, -51);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "随时选购  快速取货");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x409A70), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_chinese163, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnentershop, ui_event_btnentershop, LV_EVENT_ALL, NULL);

}
