// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: project

#include "../ui.h"

void ui_ScreenCheckout_screen_init(void)
{
    ui_ScreenCheckout = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCheckout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenCheckout, &ui_img_1062747148, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contheader = lv_obj_create(ui_ScreenCheckout);
    lv_obj_remove_style_all(ui_contheader);
    lv_obj_set_width(ui_contheader, 784);
    lv_obj_set_height(ui_contheader, 89);
    lv_obj_set_x(ui_contheader, -1);
    lv_obj_set_y(ui_contheader, -190);
    lv_obj_set_align(ui_contheader, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_contheader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelpagetitle = lv_label_create(ui_contheader);
    lv_obj_set_width(ui_labelpagetitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelpagetitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelpagetitle, 2);
    lv_obj_set_y(ui_labelpagetitle, -13);
    lv_obj_set_align(ui_labelpagetitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelpagetitle, "商品结算");
    lv_obj_set_style_text_font(ui_labelpagetitle, &ui_font_heiti301, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnbackCart = lv_btn_create(ui_contheader);
    lv_obj_set_width(ui_returnbackCart, 218);
    lv_obj_set_height(ui_returnbackCart, 50);
    lv_obj_set_x(ui_returnbackCart, -265);
    lv_obj_set_y(ui_returnbackCart, -9);
    lv_obj_set_align(ui_returnbackCart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_returnbackCart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_returnbackCart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_returnbackCart, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_returnbackCart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_returnbackCart);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "返回重新选购");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contlisttitle = lv_obj_create(ui_ScreenCheckout);
    lv_obj_remove_style_all(ui_contlisttitle);
    lv_obj_set_width(ui_contlisttitle, 606);
    lv_obj_set_height(ui_contlisttitle, 281);
    lv_obj_set_x(ui_contlisttitle, 5);
    lv_obj_set_y(ui_contlisttitle, -11);
    lv_obj_set_align(ui_contlisttitle, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_contlisttitle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_contlisttitle);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -240);
    lv_obj_set_y(ui_Label27, -113);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "商品清单");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_ScreenCheckout);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 780);
    lv_obj_set_height(ui_Container6, 87);
    lv_obj_set_x(ui_Container6, -1);
    lv_obj_set_y(ui_Container6, 187);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnsubmitorder = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_btnsubmitorder, 177);
    lv_obj_set_height(ui_btnsubmitorder, 50);
    lv_obj_set_x(ui_btnsubmitorder, 273);
    lv_obj_set_y(ui_btnsubmitorder, -5);
    lv_obj_set_align(ui_btnsubmitorder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnsubmitorder, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnsubmitorder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnsubmitorder, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnsubmitorder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_btnsubmitorder);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "提交订单");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &ui_font_fansong301, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelselectednum1 = lv_textarea_create(ui_Container6);
    lv_obj_set_width(ui_labelselectednum1, 166);
    lv_obj_set_height(ui_labelselectednum1, 52);
    lv_obj_set_x(ui_labelselectednum1, -269);
    lv_obj_set_y(ui_labelselectednum1, -2);
    lv_obj_set_align(ui_labelselectednum1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_labelselectednum1, "已选 0");
    lv_textarea_set_placeholder_text(ui_labelselectednum1, "Placeholder...");
    lv_obj_set_style_text_align(ui_labelselectednum1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelselectednum1, &ui_font_fansong30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_labelselectednum1, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_labelselectednum1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_texttotalprice1 = lv_textarea_create(ui_Container6);
    lv_obj_set_width(ui_texttotalprice1, 227);
    lv_obj_set_height(ui_texttotalprice1, 52);
    lv_obj_set_x(ui_texttotalprice1, -6);
    lv_obj_set_y(ui_texttotalprice1, -4);
    lv_obj_set_align(ui_texttotalprice1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_texttotalprice1, "合计 0元");
    lv_textarea_set_placeholder_text(ui_texttotalprice1, "Placeholder...");
    lv_obj_set_style_text_align(ui_texttotalprice1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_texttotalprice1, &ui_font_fansong30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_texttotalprice1, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_texttotalprice1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_number = lv_obj_create(ui_ScreenCheckout);
    lv_obj_remove_style_all(ui_number);
    lv_obj_set_width(ui_number, 548);
    lv_obj_set_height(ui_number, 211);
    lv_obj_set_x(ui_number, 13);
    lv_obj_set_y(ui_number, 4);
    lv_obj_set_align(ui_number, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_number, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_number, lv_color_hex(0x96CF9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_templateitem = lv_obj_create(ui_number);
    lv_obj_remove_style_all(ui_templateitem);
    lv_obj_set_width(ui_templateitem, 493);
    lv_obj_set_height(ui_templateitem, 327);
    lv_obj_set_x(ui_templateitem, -5);
    lv_obj_set_y(ui_templateitem, 15);
    lv_obj_set_align(ui_templateitem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_templateitem, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_templateitem, lv_color_hex(0x8DC19E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_templateitem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_name = lv_label_create(ui_templateitem);
    lv_obj_set_width(ui_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_name, -195);
    lv_obj_set_y(ui_name, -100);
    lv_obj_set_align(ui_name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_name, "名称");
    lv_obj_set_style_text_font(ui_name, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_num = lv_label_create(ui_templateitem);
    lv_obj_set_width(ui_num, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_num, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_num, -57);
    lv_obj_set_y(ui_num, -99);
    lv_obj_set_align(ui_num, LV_ALIGN_CENTER);
    lv_label_set_text(ui_num, "数量");
    lv_obj_set_style_text_font(ui_num, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pay = lv_label_create(ui_templateitem);
    lv_obj_set_width(ui_pay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pay, 65);
    lv_obj_set_y(ui_pay, -101);
    lv_obj_set_align(ui_pay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pay, "单价");
    lv_obj_set_style_text_font(ui_pay, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sumpay = lv_label_create(ui_templateitem);
    lv_obj_set_width(ui_sumpay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sumpay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sumpay, 192);
    lv_obj_set_y(ui_sumpay, -100);
    lv_obj_set_align(ui_sumpay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sumpay, "小计");
    lv_obj_set_style_text_font(ui_sumpay, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_returnbackCart, ui_event_returnbackCart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnsubmitorder, ui_event_btnsubmitorder, LV_EVENT_ALL, NULL);

}
