// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: project

#include "../ui.h"

void ui_ScreenCart_screen_init(void)
{
    ui_ScreenCart = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenCart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenCart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScreenCart, &ui_img_1062747148, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conttopbar = lv_obj_create(ui_ScreenCart);
    lv_obj_remove_style_all(ui_conttopbar);
    lv_obj_set_width(ui_conttopbar, 784);
    lv_obj_set_height(ui_conttopbar, 99);
    lv_obj_set_x(ui_conttopbar, 4);
    lv_obj_set_y(ui_conttopbar, -189);
    lv_obj_set_align(ui_conttopbar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_conttopbar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labeltitleshop = lv_label_create(ui_conttopbar);
    lv_obj_set_width(ui_labeltitleshop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labeltitleshop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labeltitleshop, 2);
    lv_obj_set_y(ui_labeltitleshop, -13);
    lv_obj_set_align(ui_labeltitleshop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeltitleshop, "商品选购");
    lv_obj_set_style_text_font(ui_labeltitleshop, &ui_font_heiti30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textshopname = lv_textarea_create(ui_conttopbar);
    lv_obj_set_width(ui_textshopname, 183);
    lv_obj_set_height(ui_textshopname, 51);
    lv_obj_set_x(ui_textshopname, -293);
    lv_obj_set_y(ui_textshopname, -18);
    lv_obj_set_align(ui_textshopname, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_textshopname, "自助贩卖机");
    lv_textarea_set_placeholder_text(ui_textshopname, "Placeholder...");
    lv_obj_set_style_text_color(ui_textshopname, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textshopname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textshopname, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_textshopname, lv_color_hex(0x77BB88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_textshopname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_checklist = lv_btn_create(ui_conttopbar);
    lv_obj_set_width(ui_checklist, 198);
    lv_obj_set_height(ui_checklist, 50);
    lv_obj_set_x(ui_checklist, 281);
    lv_obj_set_y(ui_checklist, -10);
    lv_obj_set_align(ui_checklist, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_checklist, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_checklist, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_checklist, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_checklist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_checklist);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "查看历史订单");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contcategory = lv_obj_create(ui_ScreenCart);
    lv_obj_remove_style_all(ui_contcategory);
    lv_obj_set_width(ui_contcategory, 135);
    lv_obj_set_height(ui_contcategory, 301);
    lv_obj_set_x(ui_contcategory, -295);
    lv_obj_set_y(ui_contcategory, -13);
    lv_obj_set_align(ui_contcategory, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_contcategory, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btncatgoods = lv_btn_create(ui_contcategory);
    lv_obj_set_width(ui_btncatgoods, 96);
    lv_obj_set_height(ui_btncatgoods, 50);
    lv_obj_set_x(ui_btncatgoods, 1);
    lv_obj_set_y(ui_btncatgoods, 83);
    lv_obj_set_align(ui_btncatgoods, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btncatgoods, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btncatgoods, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btncatgoods, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btncatgoods, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btncatgoods, lv_color_hex(0x506A4A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btncatgoods, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btncatgoods, lv_color_hex(0x79BEA6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btncatgoods, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_btncatgoods, lv_color_hex(0x559B76), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_btncatgoods, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_btncatgoods, lv_color_hex(0x80BAA8), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btncatgoods, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_Label6 = lv_label_create(ui_btncatgoods);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -1);
    lv_obj_set_y(ui_Label6, -1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "日用品");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_fansong30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_btncatall = lv_btn_create(ui_contcategory);
    lv_obj_set_width(ui_btncatall, 127);
    lv_obj_set_height(ui_btncatall, 50);
    lv_obj_set_x(ui_btncatall, 1);
    lv_obj_set_y(ui_btncatall, -105);
    lv_obj_set_align(ui_btncatall, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btncatall, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btncatall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btncatall, lv_color_hex(0x79BEA6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btncatall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btncatall, lv_color_hex(0x79BEA6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btncatall, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label4 = lv_label_create(ui_btncatall);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "全部商品");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_fansong30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btncatdrink = lv_btn_create(ui_contcategory);
    lv_obj_set_width(ui_btncatdrink, 100);
    lv_obj_set_height(ui_btncatdrink, 50);
    lv_obj_set_x(ui_btncatdrink, 1);
    lv_obj_set_y(ui_btncatdrink, -37);
    lv_obj_set_align(ui_btncatdrink, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btncatdrink, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btncatdrink, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btncatdrink, lv_color_hex(0x79BEA6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btncatdrink, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btncatdrink, lv_color_hex(0x79BEA6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btncatdrink, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label9 = lv_label_create(ui_btncatdrink);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "饮料");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_fansong30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btncatsnack = lv_btn_create(ui_contcategory);
    lv_obj_set_width(ui_btncatsnack, 100);
    lv_obj_set_height(ui_btncatsnack, 50);
    lv_obj_set_x(ui_btncatsnack, 1);
    lv_obj_set_y(ui_btncatsnack, 21);
    lv_obj_set_align(ui_btncatsnack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btncatsnack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btncatsnack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btncatsnack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btncatsnack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btncatsnack, lv_color_hex(0x79BEA6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btncatsnack, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label8 = lv_label_create(ui_btncatsnack);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "零食");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_fansong30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contgoodsdisplay = lv_obj_create(ui_ScreenCart);
    lv_obj_remove_style_all(ui_contgoodsdisplay);
    lv_obj_set_width(ui_contgoodsdisplay, 576);
    lv_obj_set_height(ui_contgoodsdisplay, 294);
    lv_obj_set_x(ui_contgoodsdisplay, 79);
    lv_obj_set_y(ui_contgoodsdisplay, -14);
    lv_obj_set_align(ui_contgoodsdisplay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contgoodsdisplay, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_set_scroll_dir(ui_contgoodsdisplay, LV_DIR_VER);

    ui_contbtncategory = lv_obj_create(ui_contgoodsdisplay);
    lv_obj_remove_style_all(ui_contbtncategory);
    lv_obj_set_width(ui_contbtncategory, 587);
    lv_obj_set_height(ui_contbtncategory, 1394);
    lv_obj_set_x(ui_contbtncategory, -4);
    lv_obj_set_y(ui_contbtncategory, 413);
    lv_obj_set_align(ui_contbtncategory, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_contbtncategory, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_containerall = lv_obj_create(ui_contbtncategory);
    lv_obj_remove_style_all(ui_containerall);
    lv_obj_set_width(ui_containerall, 576);
    lv_obj_set_height(ui_containerall, 993);
    lv_obj_set_x(ui_containerall, 1);
    lv_obj_set_y(ui_containerall, -288);
    lv_obj_set_align(ui_containerall, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_containerall, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Buttonxb = lv_btn_create(ui_containerall);
    lv_obj_set_width(ui_Buttonxb, 118);
    lv_obj_set_height(ui_Buttonxb, 50);
    lv_obj_set_x(ui_Buttonxb, -14);
    lv_obj_set_y(ui_Buttonxb, -67);
    lv_obj_set_align(ui_Buttonxb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonxb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonxb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonxb, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonxb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Buttonxb);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "雪碧4元/瓶");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonkl = lv_btn_create(ui_containerall);
    lv_obj_set_width(ui_Buttonkl, 118);
    lv_obj_set_height(ui_Buttonkl, 50);
    lv_obj_set_x(ui_Buttonkl, -184);
    lv_obj_set_y(ui_Buttonkl, -67);
    lv_obj_set_align(ui_Buttonkl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonkl, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonkl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonkl, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonkl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Buttonkl);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "可乐4元/瓶");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonnm = lv_btn_create(ui_containerall);
    lv_obj_set_width(ui_Buttonnm, 118);
    lv_obj_set_height(ui_Buttonnm, 50);
    lv_obj_set_x(ui_Buttonnm, 172);
    lv_obj_set_y(ui_Buttonnm, -66);
    lv_obj_set_align(ui_Buttonnm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonnm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonnm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonnm, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonnm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Buttonnm);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "柠檬茶5元/瓶");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonyd = lv_btn_create(ui_containerall);
    lv_obj_set_width(ui_Buttonyd, 118);
    lv_obj_set_height(ui_Buttonyd, 50);
    lv_obj_set_x(ui_Buttonyd, -192);
    lv_obj_set_y(ui_Buttonyd, 118);
    lv_obj_set_align(ui_Buttonyd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonyd, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonyd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonyd, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonyd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Buttonyd);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "运动饮料5元/瓶");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonccs = lv_btn_create(ui_containerall);
    lv_obj_set_width(ui_Buttonccs, 118);
    lv_obj_set_height(ui_Buttonccs, 50);
    lv_obj_set_x(ui_Buttonccs, -9);
    lv_obj_set_y(ui_Buttonccs, 124);
    lv_obj_set_align(ui_Buttonccs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonccs, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonccs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonccs, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonccs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Buttonccs);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "脆脆鲨2.5元/支");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonshj = lv_btn_create(ui_containerall);
    lv_obj_set_width(ui_Buttonshj, 118);
    lv_obj_set_height(ui_Buttonshj, 50);
    lv_obj_set_x(ui_Buttonshj, 178);
    lv_obj_set_y(ui_Buttonshj, 124);
    lv_obj_set_align(ui_Buttonshj, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonshj, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonshj, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonshj, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonshj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Buttonshj);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "上好佳3.5元/袋");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonqzs = lv_btn_create(ui_containerall);
    lv_obj_set_width(ui_Buttonqzs, 118);
    lv_obj_set_height(ui_Buttonqzs, 50);
    lv_obj_set_x(ui_Buttonqzs, -186);
    lv_obj_set_y(ui_Buttonqzs, 335);
    lv_obj_set_align(ui_Buttonqzs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonqzs, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonqzs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonqzs, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonqzs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Buttonqzs);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "亲嘴烧0.5元/个");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonzt = lv_btn_create(ui_containerall);
    lv_obj_set_width(ui_Buttonzt, 114);
    lv_obj_set_height(ui_Buttonzt, 50);
    lv_obj_set_x(ui_Buttonzt, -3);
    lv_obj_set_y(ui_Buttonzt, 336);
    lv_obj_set_align(ui_Buttonzt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonzt, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonzt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonzt, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonzt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Buttonzt);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "枕头20元/个");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttoncgz = lv_btn_create(ui_containerall);
    lv_obj_set_width(ui_Buttoncgz, 118);
    lv_obj_set_height(ui_Buttoncgz, 50);
    lv_obj_set_x(ui_Buttoncgz, 181);
    lv_obj_set_y(ui_Buttoncgz, 336);
    lv_obj_set_align(ui_Buttoncgz, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttoncgz, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttoncgz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttoncgz, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttoncgz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Buttoncgz);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "草稿纸5元/个");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonkz = lv_btn_create(ui_containerall);
    lv_obj_set_width(ui_Buttonkz, 118);
    lv_obj_set_height(ui_Buttonkz, 50);
    lv_obj_set_x(ui_Buttonkz, -182);
    lv_obj_set_y(ui_Buttonkz, 459);
    lv_obj_set_align(ui_Buttonkz, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonkz, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonkz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonkz, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonkz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Buttonkz);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "口罩10元/袋");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonqzs = lv_imgbtn_create(ui_containerall);
    lv_imgbtn_set_src(ui_ImgButtonqzs, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_qzs_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonqzs, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_qzs_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonqzs, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_qzs_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonqzs, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonqzs, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonqzs, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtonqzs, 136);
    lv_obj_set_width(ui_ImgButtonqzs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonqzs, -193);
    lv_obj_set_y(ui_ImgButtonqzs, 232);
    lv_obj_set_align(ui_ImgButtonqzs, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButtonqzs, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ImgButton2 = lv_imgbtn_create(ui_containerall);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_zt_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_zt_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_zt_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButton2, 141);
    lv_obj_set_width(ui_ImgButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton2, -8);
    lv_obj_set_y(ui_ImgButton2, 241);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButton2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ImgButtoncgz = lv_imgbtn_create(ui_containerall);
    lv_imgbtn_set_src(ui_ImgButtoncgz, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cgz_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtoncgz, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cgz_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtoncgz, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_cgz_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtoncgz, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtoncgz, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtoncgz, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtoncgz, 109);
    lv_obj_set_width(ui_ImgButtoncgz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtoncgz, 185);
    lv_obj_set_y(ui_ImgButtoncgz, 212);
    lv_obj_set_align(ui_ImgButtoncgz, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButtoncgz, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ImgButtonkz = lv_imgbtn_create(ui_containerall);
    lv_imgbtn_set_src(ui_ImgButtonkz, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kz_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkz, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_kz_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkz, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_kz_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkz, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkz, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkz, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtonkz, 117);
    lv_obj_set_width(ui_ImgButtonkz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonkz, -184);
    lv_obj_set_y(ui_ImgButtonkz, 387);
    lv_obj_set_align(ui_ImgButtonkz, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButtonkz, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ImgButtonshj = lv_imgbtn_create(ui_containerall);
    lv_imgbtn_set_src(ui_ImgButtonshj, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_shj_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonshj, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_shj_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonshj, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_shj_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonshj, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonshj, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonshj, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtonshj, 149);
    lv_obj_set_width(ui_ImgButtonshj, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonshj, 176);
    lv_obj_set_y(ui_ImgButtonshj, 35);
    lv_obj_set_align(ui_ImgButtonshj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButtonshj, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_imgbtnccs = lv_imgbtn_create(ui_containerall);
    lv_imgbtn_set_src(ui_imgbtnccs, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ccs_png, NULL);
    lv_imgbtn_set_src(ui_imgbtnccs, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_ccs_png, NULL);
    lv_imgbtn_set_src(ui_imgbtnccs, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_imgbtnccs, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_imgbtnccs, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_imgbtnccs, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_imgbtnccs, 85);
    lv_obj_set_width(ui_imgbtnccs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_imgbtnccs, -12);
    lv_obj_set_y(ui_imgbtnccs, 21);
    lv_obj_set_align(ui_imgbtnccs, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_imgbtnccs, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_imgbtnyd = lv_imgbtn_create(ui_containerall);
    lv_imgbtn_set_src(ui_imgbtnyd, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_yd_png, NULL);
    lv_imgbtn_set_src(ui_imgbtnyd, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_yd_png, NULL);
    lv_imgbtn_set_src(ui_imgbtnyd, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_yd_png, NULL);
    lv_imgbtn_set_src(ui_imgbtnyd, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_imgbtnyd, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_imgbtnyd, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_imgbtnyd, 113);
    lv_obj_set_width(ui_imgbtnyd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_imgbtnyd, -188);
    lv_obj_set_y(ui_imgbtnyd, 20);
    lv_obj_set_align(ui_imgbtnyd, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_imgbtnyd, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_imgbtnmite = lv_imgbtn_create(ui_containerall);
    lv_imgbtn_set_src(ui_imgbtnmite, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_nm_png, NULL);
    lv_imgbtn_set_src(ui_imgbtnmite, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_nm_png, NULL);
    lv_imgbtn_set_src(ui_imgbtnmite, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_nm_png, NULL);
    lv_imgbtn_set_src(ui_imgbtnmite, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_imgbtnmite, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_imgbtnmite, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_imgbtnmite, 141);
    lv_obj_set_width(ui_imgbtnmite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_imgbtnmite, 176);
    lv_obj_set_y(ui_imgbtnmite, -167);
    lv_obj_set_align(ui_imgbtnmite, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_imgbtnmite, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_imgbtnsprite = lv_imgbtn_create(ui_containerall);
    lv_imgbtn_set_src(ui_imgbtnsprite, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sb_png, NULL);
    lv_imgbtn_set_src(ui_imgbtnsprite, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sb_png, NULL);
    lv_imgbtn_set_src(ui_imgbtnsprite, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_sb_png, NULL);
    lv_imgbtn_set_src(ui_imgbtnsprite, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_imgbtnsprite, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_imgbtnsprite, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_imgbtnsprite, 149);
    lv_obj_set_width(ui_imgbtnsprite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_imgbtnsprite, -14);
    lv_obj_set_y(ui_imgbtnsprite, -172);
    lv_obj_set_align(ui_imgbtnsprite, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_imgbtnsprite, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_imgbtncoke = lv_imgbtn_create(ui_containerall);
    lv_imgbtn_set_src(ui_imgbtncoke, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kl_png, NULL);
    lv_imgbtn_set_src(ui_imgbtncoke, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_kl_png, NULL);
    lv_imgbtn_set_src(ui_imgbtncoke, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_kl_png, NULL);
    lv_imgbtn_set_src(ui_imgbtncoke, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_imgbtncoke, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_imgbtncoke, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_imgbtncoke, 141);
    lv_obj_set_width(ui_imgbtncoke, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_imgbtncoke, -187);
    lv_obj_set_y(ui_imgbtncoke, -180);
    lv_obj_set_align(ui_imgbtncoke, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_imgbtncoke, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_containerdrink = lv_obj_create(ui_contbtncategory);
    lv_obj_remove_style_all(ui_containerdrink);
    lv_obj_set_width(ui_containerdrink, 576);
    lv_obj_set_height(ui_containerdrink, 933);
    lv_obj_set_x(ui_containerdrink, 7);
    lv_obj_set_y(ui_containerdrink, -164);
    lv_obj_set_align(ui_containerdrink, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_containerdrink, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_containerdrink, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Buttonkl1 = lv_btn_create(ui_containerdrink);
    lv_obj_set_width(ui_Buttonkl1, 118);
    lv_obj_set_height(ui_Buttonkl1, 50);
    lv_obj_set_x(ui_Buttonkl1, -184);
    lv_obj_set_y(ui_Buttonkl1, -67);
    lv_obj_set_align(ui_Buttonkl1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonkl1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonkl1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonkl1, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonkl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Buttonkl1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "可乐4元/瓶");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonxb2 = lv_btn_create(ui_containerdrink);
    lv_obj_set_width(ui_Buttonxb2, 118);
    lv_obj_set_height(ui_Buttonxb2, 50);
    lv_obj_set_x(ui_Buttonxb2, -14);
    lv_obj_set_y(ui_Buttonxb2, -67);
    lv_obj_set_align(ui_Buttonxb2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonxb2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonxb2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonxb2, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonxb2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Buttonxb2);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "雪碧4元/瓶");
    lv_obj_set_style_text_font(ui_Label22, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonnm2 = lv_btn_create(ui_containerdrink);
    lv_obj_set_width(ui_Buttonnm2, 118);
    lv_obj_set_height(ui_Buttonnm2, 50);
    lv_obj_set_x(ui_Buttonnm2, 172);
    lv_obj_set_y(ui_Buttonnm2, -66);
    lv_obj_set_align(ui_Buttonnm2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonnm2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonnm2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonnm2, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonnm2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Buttonnm2);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "柠檬茶5元/瓶");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonyd2 = lv_btn_create(ui_containerdrink);
    lv_obj_set_width(ui_Buttonyd2, 118);
    lv_obj_set_height(ui_Buttonyd2, 50);
    lv_obj_set_x(ui_Buttonyd2, -192);
    lv_obj_set_y(ui_Buttonyd2, 118);
    lv_obj_set_align(ui_Buttonyd2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonyd2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonyd2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonyd2, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonyd2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Buttonyd2);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "运动饮料5元/瓶");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonyd = lv_imgbtn_create(ui_containerdrink);
    lv_imgbtn_set_src(ui_ImgButtonyd, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_yd_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonyd, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_yd_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonyd, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonyd, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonyd, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonyd, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtonyd, 113);
    lv_obj_set_width(ui_ImgButtonyd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonyd, -188);
    lv_obj_set_y(ui_ImgButtonyd, 20);
    lv_obj_set_align(ui_ImgButtonyd, LV_ALIGN_CENTER);

    ui_ImgButtonnm = lv_imgbtn_create(ui_containerdrink);
    lv_imgbtn_set_src(ui_ImgButtonnm, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_nm_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonnm, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_nm_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonnm, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonnm, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonnm, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonnm, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtonnm, 141);
    lv_obj_set_width(ui_ImgButtonnm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonnm, 176);
    lv_obj_set_y(ui_ImgButtonnm, -167);
    lv_obj_set_align(ui_ImgButtonnm, LV_ALIGN_CENTER);

    ui_ImgButtonsb = lv_imgbtn_create(ui_containerdrink);
    lv_imgbtn_set_src(ui_ImgButtonsb, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sb_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonsb, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sb_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonsb, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonsb, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonsb, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonsb, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtonsb, 149);
    lv_obj_set_width(ui_ImgButtonsb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonsb, -14);
    lv_obj_set_y(ui_ImgButtonsb, -172);
    lv_obj_set_align(ui_ImgButtonsb, LV_ALIGN_CENTER);

    ui_ImgButtonkl = lv_imgbtn_create(ui_containerdrink);
    lv_imgbtn_set_src(ui_ImgButtonkl, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kl_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkl, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_kl_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkl, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkl, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkl, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkl, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtonkl, 141);
    lv_obj_set_width(ui_ImgButtonkl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonkl, -187);
    lv_obj_set_y(ui_ImgButtonkl, -180);
    lv_obj_set_align(ui_ImgButtonkl, LV_ALIGN_CENTER);

    ui_containersnack = lv_obj_create(ui_contbtncategory);
    lv_obj_remove_style_all(ui_containersnack);
    lv_obj_set_width(ui_containersnack, 576);
    lv_obj_set_height(ui_containersnack, 933);
    lv_obj_set_x(ui_containersnack, -9);
    lv_obj_set_y(ui_containersnack, -183);
    lv_obj_set_align(ui_containersnack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_containersnack, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_containersnack, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Buttonccs2 = lv_btn_create(ui_containersnack);
    lv_obj_set_width(ui_Buttonccs2, 118);
    lv_obj_set_height(ui_Buttonccs2, 50);
    lv_obj_set_x(ui_Buttonccs2, -8);
    lv_obj_set_y(ui_Buttonccs2, -55);
    lv_obj_set_align(ui_Buttonccs2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonccs2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonccs2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonccs2, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonccs2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_Buttonccs2);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "脆脆鲨2.5元/支");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonshj2 = lv_btn_create(ui_containersnack);
    lv_obj_set_width(ui_Buttonshj2, 118);
    lv_obj_set_height(ui_Buttonshj2, 50);
    lv_obj_set_x(ui_Buttonshj2, 168);
    lv_obj_set_y(ui_Buttonshj2, -56);
    lv_obj_set_align(ui_Buttonshj2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonshj2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonshj2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonshj2, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonshj2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_Buttonshj2);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "上好佳3.5元/袋");
    lv_obj_set_style_text_font(ui_Label36, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonqzs2 = lv_btn_create(ui_containersnack);
    lv_obj_set_width(ui_Buttonqzs2, 118);
    lv_obj_set_height(ui_Buttonqzs2, 50);
    lv_obj_set_x(ui_Buttonqzs2, -178);
    lv_obj_set_y(ui_Buttonqzs2, -56);
    lv_obj_set_align(ui_Buttonqzs2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonqzs2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonqzs2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonqzs2, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonqzs2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Buttonqzs2);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "亲嘴烧0.5元/个");
    lv_obj_set_style_text_font(ui_Label37, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonqzs2 = lv_imgbtn_create(ui_containersnack);
    lv_imgbtn_set_src(ui_ImgButtonqzs2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_qzs_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonqzs2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_qzs_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonqzs2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonqzs2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonqzs2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonqzs2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtonqzs2, 136);
    lv_obj_set_width(ui_ImgButtonqzs2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonqzs2, -185);
    lv_obj_set_y(ui_ImgButtonqzs2, -168);
    lv_obj_set_align(ui_ImgButtonqzs2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButtonqzs2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ImgButtonshj2 = lv_imgbtn_create(ui_containersnack);
    lv_imgbtn_set_src(ui_ImgButtonshj2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_shj_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonshj2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_shj_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonshj2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonshj2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonshj2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonshj2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtonshj2, 149);
    lv_obj_set_width(ui_ImgButtonshj2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonshj2, 173);
    lv_obj_set_y(ui_ImgButtonshj2, -153);
    lv_obj_set_align(ui_ImgButtonshj2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButtonshj2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ImgButtonccs2 = lv_imgbtn_create(ui_containersnack);
    lv_imgbtn_set_src(ui_ImgButtonccs2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ccs_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonccs2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_ccs_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonccs2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonccs2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonccs2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonccs2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtonccs2, 85);
    lv_obj_set_width(ui_ImgButtonccs2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonccs2, -8);
    lv_obj_set_y(ui_ImgButtonccs2, -177);
    lv_obj_set_align(ui_ImgButtonccs2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButtonccs2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_containergoods = lv_obj_create(ui_contbtncategory);
    lv_obj_remove_style_all(ui_containergoods);
    lv_obj_set_width(ui_containergoods, 576);
    lv_obj_set_height(ui_containergoods, 933);
    lv_obj_set_x(ui_containergoods, 3);
    lv_obj_set_y(ui_containergoods, -198);
    lv_obj_set_align(ui_containergoods, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_containergoods, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_containergoods, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Buttonzt2 = lv_btn_create(ui_containergoods);
    lv_obj_set_width(ui_Buttonzt2, 114);
    lv_obj_set_height(ui_Buttonzt2, 50);
    lv_obj_set_x(ui_Buttonzt2, -7);
    lv_obj_set_y(ui_Buttonzt2, -55);
    lv_obj_set_align(ui_Buttonzt2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonzt2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonzt2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonzt2, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonzt2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_Buttonzt2);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "枕头20元/个");
    lv_obj_set_style_text_font(ui_Label48, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttoncgz2 = lv_btn_create(ui_containergoods);
    lv_obj_set_width(ui_Buttoncgz2, 118);
    lv_obj_set_height(ui_Buttoncgz2, 50);
    lv_obj_set_x(ui_Buttoncgz2, 175);
    lv_obj_set_y(ui_Buttoncgz2, -59);
    lv_obj_set_align(ui_Buttoncgz2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttoncgz2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttoncgz2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttoncgz2, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttoncgz2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Buttoncgz2);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "草稿纸5元/个");
    lv_obj_set_style_text_font(ui_Label49, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonkz2 = lv_btn_create(ui_containergoods);
    lv_obj_set_width(ui_Buttonkz2, 130);
    lv_obj_set_height(ui_Buttonkz2, 50);
    lv_obj_set_x(ui_Buttonkz2, -171);
    lv_obj_set_y(ui_Buttonkz2, -58);
    lv_obj_set_align(ui_Buttonkz2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonkz2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonkz2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonkz2, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonkz2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_Buttonkz2);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "口罩10元/袋");
    lv_obj_set_style_text_font(ui_Label50, &ui_font_fansong16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonzt = lv_imgbtn_create(ui_containergoods);
    lv_imgbtn_set_src(ui_ImgButtonzt, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_zt_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonzt, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_zt_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonzt, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonzt, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonzt, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonzt, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtonzt, 141);
    lv_obj_set_width(ui_ImgButtonzt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonzt, -9);
    lv_obj_set_y(ui_ImgButtonzt, -157);
    lv_obj_set_align(ui_ImgButtonzt, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButtonzt, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ImgButtoncgz2 = lv_imgbtn_create(ui_containergoods);
    lv_imgbtn_set_src(ui_ImgButtoncgz2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cgz_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtoncgz2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cgz_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtoncgz2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtoncgz2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtoncgz2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtoncgz2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtoncgz2, 109);
    lv_obj_set_width(ui_ImgButtoncgz2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtoncgz2, 163);
    lv_obj_set_y(ui_ImgButtoncgz2, -171);
    lv_obj_set_align(ui_ImgButtoncgz2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButtoncgz2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ImgButtonkz2 = lv_imgbtn_create(ui_containergoods);
    lv_imgbtn_set_src(ui_ImgButtonkz2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kz_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkz2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_kz_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkz2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkz2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkz2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonkz2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButtonkz2, 117);
    lv_obj_set_width(ui_ImgButtonkz2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonkz2, -182);
    lv_obj_set_y(ui_ImgButtonkz2, -145);
    lv_obj_set_align(ui_ImgButtonkz2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButtonkz2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_ScreenCart);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 757);
    lv_obj_set_height(ui_Container9, 87);
    lv_obj_set_x(ui_Container9, 1);
    lv_obj_set_y(ui_Container9, 189);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btngotocheckout = lv_btn_create(ui_Container9);
    lv_obj_set_width(ui_btngotocheckout, 177);
    lv_obj_set_height(ui_btngotocheckout, 50);
    lv_obj_set_x(ui_btngotocheckout, 275);
    lv_obj_set_y(ui_btngotocheckout, 5);
    lv_obj_set_align(ui_btngotocheckout, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btngotocheckout, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btngotocheckout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btngotocheckout, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btngotocheckout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_btngotocheckout);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "去结算");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_fansong301, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelselectednum = lv_textarea_create(ui_Container9);
    lv_obj_set_width(ui_labelselectednum, 166);
    lv_obj_set_height(ui_labelselectednum, 52);
    lv_obj_set_x(ui_labelselectednum, -273);
    lv_obj_set_y(ui_labelselectednum, 5);
    lv_obj_set_align(ui_labelselectednum, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_labelselectednum, "已选 0");
    lv_textarea_set_placeholder_text(ui_labelselectednum, "Placeholder...");
    lv_obj_set_style_text_font(ui_labelselectednum, &ui_font_fansong30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_labelselectednum, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_labelselectednum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_texttotalprice = lv_textarea_create(ui_Container9);
    lv_obj_set_width(ui_texttotalprice, 236);
    lv_obj_set_height(ui_texttotalprice, 52);
    lv_obj_set_x(ui_texttotalprice, 6);
    lv_obj_set_y(ui_texttotalprice, 5);
    lv_obj_set_align(ui_texttotalprice, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_texttotalprice, "合计0 元");
    lv_textarea_set_placeholder_text(ui_texttotalprice, "Placeholder...");
    lv_obj_set_style_text_font(ui_texttotalprice, &ui_font_fansong30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_texttotalprice, lv_color_hex(0x77BE91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_texttotalprice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_checklist, ui_event_checklist, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btncatgoods, ui_event_btncatgoods, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btncatall, ui_event_btncatall, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btncatdrink, ui_event_btncatdrink, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btncatsnack, ui_event_btncatsnack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonxb, ui_event_Buttonxb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonkl, ui_event_Buttonkl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonnm, ui_event_Buttonnm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonyd, ui_event_Buttonyd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonccs, ui_event_Buttonccs, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonshj, ui_event_Buttonshj, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonqzs, ui_event_Buttonqzs, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonzt, ui_event_Buttonzt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttoncgz, ui_event_Buttoncgz, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonkz, ui_event_Buttonkz, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonkl1, ui_event_Buttonkl1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonxb2, ui_event_Buttonxb2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonnm2, ui_event_Buttonnm2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonyd2, ui_event_Buttonyd2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonccs2, ui_event_Buttonccs2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonshj2, ui_event_Buttonshj2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonqzs2, ui_event_Buttonqzs2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonzt2, ui_event_Buttonzt2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttoncgz2, ui_event_Buttoncgz2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonkz2, ui_event_Buttonkz2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btngotocheckout, ui_event_btngotocheckout, LV_EVENT_ALL, NULL);

}
