// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: project

#include "../ui.h"

void ui_ScreenPaySuccess_screen_init(void)
{
    ui_ScreenPaySuccess = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPaySuccess, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenPaySuccess, &ui_img_1062747148, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_ScreenPaySuccess);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, -4);
    lv_obj_set_y(ui_Label41, -202);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "支付成功");
    lv_obj_set_style_text_font(ui_Label41, &ui_font_heiti301, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_ScreenPaySuccess);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, 1);
    lv_obj_set_y(ui_Label42, -94);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "支付成功！");
    lv_obj_set_style_text_font(ui_Label42, &ui_font_heiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea12 = lv_textarea_create(ui_ScreenPaySuccess);
    lv_obj_set_width(ui_TextArea12, 401);
    lv_obj_set_height(ui_TextArea12, 105);
    lv_obj_set_x(ui_TextArea12, 10);
    lv_obj_set_y(ui_TextArea12, 6);
    lv_obj_set_align(ui_TextArea12, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea12, "商品正在出货\n请取走商品    请取走商品");
    lv_textarea_set_placeholder_text(ui_TextArea12, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextArea12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea12, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea12, lv_color_hex(0x77BB88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label43 = lv_label_create(ui_ScreenPaySuccess);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, 14);
    lv_obj_set_y(ui_Label43, 103);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "10秒后自动返回登录界面");
    lv_obj_set_style_text_font(ui_Label43, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea13 = lv_textarea_create(ui_ScreenPaySuccess);
    lv_obj_set_width(ui_TextArea13, 266);
    lv_obj_set_height(ui_TextArea13, 58);
    lv_obj_set_x(ui_TextArea13, 193);
    lv_obj_set_y(ui_TextArea13, 162);
    lv_obj_set_align(ui_TextArea13, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea13, "立即返回登录界面");
    lv_textarea_set_placeholder_text(ui_TextArea13, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextArea13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea13, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea13, lv_color_hex(0x77BB88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_TextArea13, ui_event_TextArea13, LV_EVENT_ALL, NULL);

}
