// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: project

#include "../ui.h"

void ui_usrlogin_screen_init(void)
{
    ui_usrlogin = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_usrlogin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_usrlogin, &ui_img_1062747148, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_usrname = lv_textarea_create(ui_usrlogin);
    lv_obj_set_width(ui_usrname, 366);
    lv_obj_set_height(ui_usrname, 62);
    lv_obj_set_x(ui_usrname, -6);
    lv_obj_set_y(ui_usrname, -107);
    lv_obj_set_align(ui_usrname, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_usrname, "username");



    ui_Keyboard1 = lv_keyboard_create(ui_usrlogin);
    lv_obj_set_width(ui_Keyboard1, 776);
    lv_obj_set_height(ui_Keyboard1, 212);
    lv_obj_set_x(ui_Keyboard1, 3);
    lv_obj_set_y(ui_Keyboard1, 129);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_login = lv_btn_create(ui_usrlogin);
    lv_obj_set_width(ui_login, 124);
    lv_obj_set_height(ui_login, 56);
    lv_obj_set_x(ui_login, -104);
    lv_obj_set_y(ui_login, -11);
    lv_obj_set_align(ui_login, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_login, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_login, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_login, lv_color_hex(0x78B880), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_login, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_login);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "登录");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_fansong30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_register = lv_btn_create(ui_usrlogin);
    lv_obj_set_width(ui_register, 124);
    lv_obj_set_height(ui_register, 56);
    lv_obj_set_x(ui_register, 97);
    lv_obj_set_y(ui_register, -11);
    lv_obj_set_align(ui_register, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_register, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_register, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_register, lv_color_hex(0x78B880), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_register, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_register);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "注册");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_fansong30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_usrlogin);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -276);
    lv_obj_set_y(ui_Label26, -183);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "请登录，若未注册请注册");
    lv_obj_set_style_text_font(ui_Label26, &ui_font_chinse16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_usrname, ui_event_usrname, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_login, ui_event_login, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_register, ui_event_register, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_usrlogin, ui_event_usrlogin, LV_EVENT_ALL, NULL);

}
