SET(SOURCES screens/ui_usrlogin.c
    screens/ui_ScreenMain.c
    screens/ui_ScreenCart.c
    screens/ui_ScreenCheckout.c
    screens/ui_ScreenPay.c
    screens/ui_ScreenPaySuccess.c
    screens/ui_sign_up.c
    screens/ui_historylist.c
    ui.c
    components/ui_comp_hook.c
    ui_helpers.c
    ui_events.c
    images/ui_img_1062747148.c
    images/ui_img_435601465.c
    images/ui_img_qzs_png.c
    images/ui_img_zt_png.c
    images/ui_img_cgz_png.c
    images/ui_img_kz_png.c
    images/ui_img_shj_png.c
    images/ui_img_ccs_png.c
    images/ui_img_yd_png.c
    images/ui_img_nm_png.c
    images/ui_img_sb_png.c
    images/ui_img_kl_png.c
    images/ui_img_ewm_png.c
    ui_temporary_image.c
    fonts/ui_font_chinese162.c
    fonts/ui_font_chinese163.c
    fonts/ui_font_chinese20.c
    fonts/ui_font_chinese30.c
    fonts/ui_font_chinese36.c
    fonts/ui_font_chinse16.c
    fonts/ui_font_fansong16.c
    fonts/ui_font_fansong30.c
    fonts/ui_font_fansong301.c
    fonts/ui_font_heiti30.c
    fonts/ui_font_heiti301.c
    fonts/ui_font_heiti36.c)

add_library(ui ${SOURCES})
