// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_usrlogin
void ui_usrlogin_screen_init(void);
void ui_event_usrlogin(lv_event_t * e);
lv_obj_t * ui_usrlogin;
void ui_event_usrname(lv_event_t * e);
lv_obj_t * ui_usrname;
lv_obj_t * ui_Keyboard1;
void ui_event_login(lv_event_t * e);
lv_obj_t * ui_login;
lv_obj_t * ui_Label1;
void ui_event_register(lv_event_t * e);
lv_obj_t * ui_register;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Label26;


// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
lv_obj_t * ui_ScreenMain;
void ui_event_btnentershop(lv_event_t * e);
lv_obj_t * ui_btnentershop;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_labeltitle;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Image6;
lv_obj_t * ui_labelservicetip1;
lv_obj_t * ui_Label7;


// SCREEN: ui_ScreenCart
void ui_ScreenCart_screen_init(void);
lv_obj_t * ui_ScreenCart;
lv_obj_t * ui_conttopbar;
lv_obj_t * ui_labeltitleshop;
lv_obj_t * ui_textshopname;
void ui_event_checklist(lv_event_t * e);
lv_obj_t * ui_checklist;
lv_obj_t * ui_Label38;
lv_obj_t * ui_contcategory;
void ui_event_btncatgoods(lv_event_t * e);
lv_obj_t * ui_btncatgoods;
lv_obj_t * ui_Label6;
void ui_event_btncatall(lv_event_t * e);
lv_obj_t * ui_btncatall;
lv_obj_t * ui_Label4;
void ui_event_btncatdrink(lv_event_t * e);
lv_obj_t * ui_btncatdrink;
lv_obj_t * ui_Label9;
void ui_event_btncatsnack(lv_event_t * e);
lv_obj_t * ui_btncatsnack;
lv_obj_t * ui_Label8;
lv_obj_t * ui_contgoodsdisplay;
lv_obj_t * ui_contbtncategory;
lv_obj_t * ui_containerall;
void ui_event_Buttonxb(lv_event_t * e);
lv_obj_t * ui_Buttonxb;
lv_obj_t * ui_Label13;
void ui_event_Buttonkl(lv_event_t * e);
lv_obj_t * ui_Buttonkl;
lv_obj_t * ui_Label11;
void ui_event_Buttonnm(lv_event_t * e);
lv_obj_t * ui_Buttonnm;
lv_obj_t * ui_Label14;
void ui_event_Buttonyd(lv_event_t * e);
lv_obj_t * ui_Buttonyd;
lv_obj_t * ui_Label15;
void ui_event_Buttonccs(lv_event_t * e);
lv_obj_t * ui_Buttonccs;
lv_obj_t * ui_Label16;
void ui_event_Buttonshj(lv_event_t * e);
lv_obj_t * ui_Buttonshj;
lv_obj_t * ui_Label17;
void ui_event_Buttonqzs(lv_event_t * e);
lv_obj_t * ui_Buttonqzs;
lv_obj_t * ui_Label18;
void ui_event_Buttonzt(lv_event_t * e);
lv_obj_t * ui_Buttonzt;
lv_obj_t * ui_Label19;
void ui_event_Buttoncgz(lv_event_t * e);
lv_obj_t * ui_Buttoncgz;
lv_obj_t * ui_Label20;
void ui_event_Buttonkz(lv_event_t * e);
lv_obj_t * ui_Buttonkz;
lv_obj_t * ui_Label21;
lv_obj_t * ui_ImgButtonqzs;
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui_ImgButtoncgz;
lv_obj_t * ui_ImgButtonkz;
lv_obj_t * ui_ImgButtonshj;
lv_obj_t * ui_imgbtnccs;
lv_obj_t * ui_imgbtnyd;
lv_obj_t * ui_imgbtnmite;
lv_obj_t * ui_imgbtnsprite;
lv_obj_t * ui_imgbtncoke;
lv_obj_t * ui_containerdrink;
void ui_event_Buttonkl1(lv_event_t * e);
lv_obj_t * ui_Buttonkl1;
lv_obj_t * ui_Label12;
void ui_event_Buttonxb2(lv_event_t * e);
lv_obj_t * ui_Buttonxb2;
lv_obj_t * ui_Label22;
void ui_event_Buttonnm2(lv_event_t * e);
lv_obj_t * ui_Buttonnm2;
lv_obj_t * ui_Label23;
void ui_event_Buttonyd2(lv_event_t * e);
lv_obj_t * ui_Buttonyd2;
lv_obj_t * ui_Label24;
lv_obj_t * ui_ImgButtonyd;
lv_obj_t * ui_ImgButtonnm;
lv_obj_t * ui_ImgButtonsb;
lv_obj_t * ui_ImgButtonkl;
lv_obj_t * ui_containersnack;
void ui_event_Buttonccs2(lv_event_t * e);
lv_obj_t * ui_Buttonccs2;
lv_obj_t * ui_Label35;
void ui_event_Buttonshj2(lv_event_t * e);
lv_obj_t * ui_Buttonshj2;
lv_obj_t * ui_Label36;
void ui_event_Buttonqzs2(lv_event_t * e);
lv_obj_t * ui_Buttonqzs2;
lv_obj_t * ui_Label37;
lv_obj_t * ui_ImgButtonqzs2;
lv_obj_t * ui_ImgButtonshj2;
lv_obj_t * ui_ImgButtonccs2;
lv_obj_t * ui_containergoods;
void ui_event_Buttonzt2(lv_event_t * e);
lv_obj_t * ui_Buttonzt2;
lv_obj_t * ui_Label48;
void ui_event_Buttoncgz2(lv_event_t * e);
lv_obj_t * ui_Buttoncgz2;
lv_obj_t * ui_Label49;
void ui_event_Buttonkz2(lv_event_t * e);
lv_obj_t * ui_Buttonkz2;
lv_obj_t * ui_Label50;
lv_obj_t * ui_ImgButtonzt;
lv_obj_t * ui_ImgButtoncgz2;
lv_obj_t * ui_ImgButtonkz2;
lv_obj_t * ui_Container9;
void ui_event_btngotocheckout(lv_event_t * e);
lv_obj_t * ui_btngotocheckout;
lv_obj_t * ui_Label25;
lv_obj_t * ui_labelselectednum;
lv_obj_t * ui_texttotalprice;


// SCREEN: ui_ScreenCheckout
void ui_ScreenCheckout_screen_init(void);
lv_obj_t * ui_ScreenCheckout;
lv_obj_t * ui_contheader;
lv_obj_t * ui_labelpagetitle;
void ui_event_returnbackCart(lv_event_t * e);
lv_obj_t * ui_returnbackCart;
lv_obj_t * ui_Label10;
lv_obj_t * ui_contlisttitle;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Container6;
void ui_event_btnsubmitorder(lv_event_t * e);
lv_obj_t * ui_btnsubmitorder;
lv_obj_t * ui_Label31;
lv_obj_t * ui_labelselectednum1;
lv_obj_t * ui_texttotalprice1;
lv_obj_t * ui_number;
lv_obj_t * ui_templateitem;
lv_obj_t * ui_name;
lv_obj_t * ui_num;
lv_obj_t * ui_pay;
lv_obj_t * ui_sumpay;


// SCREEN: ui_ScreenPay
void ui_ScreenPay_screen_init(void);
lv_obj_t * ui_ScreenPay;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Label28;
void ui_event_TextArea9(lv_event_t * e);
lv_obj_t * ui_TextArea9;
lv_obj_t * ui_shouldpay;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Image20;
void ui_event_surepay(lv_event_t * e);
lv_obj_t * ui_surepay;
lv_obj_t * ui_Label30;
void ui_event_cancelpay(lv_event_t * e);
lv_obj_t * ui_cancelpay;
lv_obj_t * ui_Label40;


// SCREEN: ui_ScreenPaySuccess
void ui_ScreenPaySuccess_screen_init(void);
lv_obj_t * ui_ScreenPaySuccess;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Label42;
lv_obj_t * ui_TextArea12;
lv_obj_t * ui_Label43;
void ui_event_TextArea13(lv_event_t * e);
lv_obj_t * ui_TextArea13;


// SCREEN: ui_sign_up
void ui_sign_up_screen_init(void);
lv_obj_t * ui_sign_up;
void ui_event_usrname2(lv_event_t * e);
lv_obj_t * ui_usrname2;
void ui_event_usrname3(lv_event_t * e);
lv_obj_t * ui_usrname3;
lv_obj_t * ui_Keyboard2;
void ui_event_returnlogin(lv_event_t * e);
lv_obj_t * ui_returnlogin;
lv_obj_t * ui_Label33;
void ui_event_returnlogin2(lv_event_t * e);
lv_obj_t * ui_returnlogin2;
lv_obj_t * ui_Label44;


// SCREEN: ui_historylist
void ui_historylist_screen_init(void);
lv_obj_t * ui_historylist;
lv_obj_t * ui_list;
lv_obj_t * ui_templateitem2;
lv_obj_t * ui_day;
lv_obj_t * ui_num2;
lv_obj_t * ui_total;
lv_obj_t * ui_digtal;
void ui_event_returnscreencart(lv_event_t * e);
lv_obj_t * ui_returnscreencart;
lv_obj_t * ui_Label34;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1654757344[2] = {&ui_img_1062747148, &ui_img_435601465};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_usrlogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_usrname(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_usrname);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_login(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btngotomain(e);
    }
}
void ui_event_register(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_sign_up, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_sign_up_screen_init);
    }
}
void ui_event_btnentershop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenCart, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenCart_screen_init);
    }
}
void ui_event_checklist(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_historylist, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_historylist_screen_init);
    }
}
void ui_event_btncatgoods(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_containerall, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_containerdrink, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_containersnack, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_containergoods, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_btncatall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_containerall, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_containerdrink, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_containersnack, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_containergoods, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_btncatdrink(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_containerall, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_containerdrink, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_containersnack, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_containergoods, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_btncatsnack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_containerall, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_containersnack, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_containergoods, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_containerdrink, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Buttonxb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_sprite_cb(e);
    }
}
void ui_event_Buttonkl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_coke_cb(e);
    }
}
void ui_event_Buttonnm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_lemon_tea_cb(e);
    }
}
void ui_event_Buttonyd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_sport_drink_cb(e);
    }
}
void ui_event_Buttonccs(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_crunchshark_cb(e);
    }
}
void ui_event_Buttonshj(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_crunchshark_cb(e);
    }
}
void ui_event_Buttonqzs(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_kissburn_cb(e);
    }
}
void ui_event_Buttonzt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_pillow_cb(e);
    }
}
void ui_event_Buttoncgz(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_pillow_cb(e);
    }
}
void ui_event_Buttonkz(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_mask_cb(e);
    }
}
void ui_event_Buttonkl1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_coke_cb(e);
    }
}
void ui_event_Buttonxb2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_sprite_cb(e);
    }
}
void ui_event_Buttonnm2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_lemon_tea_cb(e);
    }
}
void ui_event_Buttonyd2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_sport_drink_cb(e);
    }
}
void ui_event_Buttonccs2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_crunchshark_cb(e);
    }
}
void ui_event_Buttonshj2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_haojia_cb(e);
    }
}
void ui_event_Buttonqzs2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_kissburn_cb(e);
    }
}
void ui_event_Buttonzt2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_pillow_cb(e);
    }
}
void ui_event_Buttoncgz2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_paper_cb(e);
    }
}
void ui_event_Buttonkz2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_mask_cb(e);
    }
}
void ui_event_btngotocheckout(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenCheckout, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScreenCheckout_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        btngotocheckout(e);
    }
}
void ui_event_returnbackCart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenCart, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScreenCart_screen_init);
    }
}
void ui_event_btnsubmitorder(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenPay, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenPay_screen_init);
    }
}
void ui_event_TextArea9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenCheckout, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScreenCheckout_screen_init);
    }
}
void ui_event_surepay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenPaySuccess, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenPaySuccess_screen_init);
    }
}
void ui_event_cancelpay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScreenMain_screen_init);
    }
}
void ui_event_TextArea13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, &ui_ScreenMain_screen_init);
    }
}
void ui_event_usrname2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_usrname2);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_usrname3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_usrname3);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_returnlogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_usrlogin, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_usrlogin_screen_init);
    }
}
void ui_event_returnlogin2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        returnusrlogin(e);
    }
}
void ui_event_returnscreencart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenCart, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_ScreenCart_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_usrlogin_screen_init();
    ui_ScreenMain_screen_init();
    ui_ScreenCart_screen_init();
    ui_ScreenCheckout_screen_init();
    ui_ScreenPay_screen_init();
    ui_ScreenPaySuccess_screen_init();
    ui_sign_up_screen_init();
    ui_historylist_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_usrlogin);
}
