// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: project

#ifndef _PROJECT_UI_H
#define _PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_usrlogin
void ui_usrlogin_screen_init(void);
void ui_event_usrlogin(lv_event_t * e);
extern lv_obj_t * ui_usrlogin;
void ui_event_usrname(lv_event_t * e);
extern lv_obj_t * ui_usrname;
extern lv_obj_t * ui_Keyboard1;
void ui_event_login(lv_event_t * e);
extern lv_obj_t * ui_login;
extern lv_obj_t * ui_Label1;
void ui_event_register(lv_event_t * e);
extern lv_obj_t * ui_register;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label26;
// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t * ui_ScreenMain;
void ui_event_btnentershop(lv_event_t * e);
extern lv_obj_t * ui_btnentershop;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_labeltitle;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_labelservicetip1;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_ScreenCart
void ui_ScreenCart_screen_init(void);
extern lv_obj_t * ui_ScreenCart;
extern lv_obj_t * ui_conttopbar;
extern lv_obj_t * ui_labeltitleshop;
extern lv_obj_t * ui_textshopname;
void ui_event_checklist(lv_event_t * e);
extern lv_obj_t * ui_checklist;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_contcategory;
void ui_event_btncatgoods(lv_event_t * e);
extern lv_obj_t * ui_btncatgoods;
extern lv_obj_t * ui_Label6;
void ui_event_btncatall(lv_event_t * e);
extern lv_obj_t * ui_btncatall;
extern lv_obj_t * ui_Label4;
void ui_event_btncatdrink(lv_event_t * e);
extern lv_obj_t * ui_btncatdrink;
extern lv_obj_t * ui_Label9;
void ui_event_btncatsnack(lv_event_t * e);
extern lv_obj_t * ui_btncatsnack;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_contgoodsdisplay;
extern lv_obj_t * ui_contbtncategory;
extern lv_obj_t * ui_containerall;
void ui_event_Buttonxb(lv_event_t * e);
extern lv_obj_t * ui_Buttonxb;
extern lv_obj_t * ui_Label13;
void ui_event_Buttonkl(lv_event_t * e);
extern lv_obj_t * ui_Buttonkl;
extern lv_obj_t * ui_Label11;
void ui_event_Buttonnm(lv_event_t * e);
extern lv_obj_t * ui_Buttonnm;
extern lv_obj_t * ui_Label14;
void ui_event_Buttonyd(lv_event_t * e);
extern lv_obj_t * ui_Buttonyd;
extern lv_obj_t * ui_Label15;
void ui_event_Buttonccs(lv_event_t * e);
extern lv_obj_t * ui_Buttonccs;
extern lv_obj_t * ui_Label16;
void ui_event_Buttonshj(lv_event_t * e);
extern lv_obj_t * ui_Buttonshj;
extern lv_obj_t * ui_Label17;
void ui_event_Buttonqzs(lv_event_t * e);
extern lv_obj_t * ui_Buttonqzs;
extern lv_obj_t * ui_Label18;
void ui_event_Buttonzt(lv_event_t * e);
extern lv_obj_t * ui_Buttonzt;
extern lv_obj_t * ui_Label19;
void ui_event_Buttoncgz(lv_event_t * e);
extern lv_obj_t * ui_Buttoncgz;
extern lv_obj_t * ui_Label20;
void ui_event_Buttonkz(lv_event_t * e);
extern lv_obj_t * ui_Buttonkz;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_ImgButtonqzs;
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_ImgButtoncgz;
extern lv_obj_t * ui_ImgButtonkz;
extern lv_obj_t * ui_ImgButtonshj;
extern lv_obj_t * ui_imgbtnccs;
extern lv_obj_t * ui_imgbtnyd;
extern lv_obj_t * ui_imgbtnmite;
extern lv_obj_t * ui_imgbtnsprite;
extern lv_obj_t * ui_imgbtncoke;
extern lv_obj_t * ui_containerdrink;
void ui_event_Buttonkl1(lv_event_t * e);
extern lv_obj_t * ui_Buttonkl1;
extern lv_obj_t * ui_Label12;
void ui_event_Buttonxb2(lv_event_t * e);
extern lv_obj_t * ui_Buttonxb2;
extern lv_obj_t * ui_Label22;
void ui_event_Buttonnm2(lv_event_t * e);
extern lv_obj_t * ui_Buttonnm2;
extern lv_obj_t * ui_Label23;
void ui_event_Buttonyd2(lv_event_t * e);
extern lv_obj_t * ui_Buttonyd2;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_ImgButtonyd;
extern lv_obj_t * ui_ImgButtonnm;
extern lv_obj_t * ui_ImgButtonsb;
extern lv_obj_t * ui_ImgButtonkl;
extern lv_obj_t * ui_containersnack;
void ui_event_Buttonccs2(lv_event_t * e);
extern lv_obj_t * ui_Buttonccs2;
extern lv_obj_t * ui_Label35;
void ui_event_Buttonshj2(lv_event_t * e);
extern lv_obj_t * ui_Buttonshj2;
extern lv_obj_t * ui_Label36;
void ui_event_Buttonqzs2(lv_event_t * e);
extern lv_obj_t * ui_Buttonqzs2;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_ImgButtonqzs2;
extern lv_obj_t * ui_ImgButtonshj2;
extern lv_obj_t * ui_ImgButtonccs2;
extern lv_obj_t * ui_containergoods;
void ui_event_Buttonzt2(lv_event_t * e);
extern lv_obj_t * ui_Buttonzt2;
extern lv_obj_t * ui_Label48;
void ui_event_Buttoncgz2(lv_event_t * e);
extern lv_obj_t * ui_Buttoncgz2;
extern lv_obj_t * ui_Label49;
void ui_event_Buttonkz2(lv_event_t * e);
extern lv_obj_t * ui_Buttonkz2;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_ImgButtonzt;
extern lv_obj_t * ui_ImgButtoncgz2;
extern lv_obj_t * ui_ImgButtonkz2;
extern lv_obj_t * ui_Container9;
void ui_event_btngotocheckout(lv_event_t * e);
extern lv_obj_t * ui_btngotocheckout;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_labelselectednum;
extern lv_obj_t * ui_texttotalprice;
// SCREEN: ui_ScreenCheckout
void ui_ScreenCheckout_screen_init(void);
extern lv_obj_t * ui_ScreenCheckout;
extern lv_obj_t * ui_contheader;
extern lv_obj_t * ui_labelpagetitle;
void ui_event_returnbackCart(lv_event_t * e);
extern lv_obj_t * ui_returnbackCart;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_contlisttitle;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Container6;
void ui_event_btnsubmitorder(lv_event_t * e);
extern lv_obj_t * ui_btnsubmitorder;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_labelselectednum1;
extern lv_obj_t * ui_texttotalprice1;
extern lv_obj_t * ui_number;
extern lv_obj_t * ui_templateitem;
extern lv_obj_t * ui_name;
extern lv_obj_t * ui_num;
extern lv_obj_t * ui_pay;
extern lv_obj_t * ui_sumpay;
// SCREEN: ui_ScreenPay
void ui_ScreenPay_screen_init(void);
extern lv_obj_t * ui_ScreenPay;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label28;
void ui_event_TextArea9(lv_event_t * e);
extern lv_obj_t * ui_TextArea9;
extern lv_obj_t * ui_shouldpay;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Image20;
void ui_event_surepay(lv_event_t * e);
extern lv_obj_t * ui_surepay;
extern lv_obj_t * ui_Label30;
void ui_event_cancelpay(lv_event_t * e);
extern lv_obj_t * ui_cancelpay;
extern lv_obj_t * ui_Label40;
// SCREEN: ui_ScreenPaySuccess
void ui_ScreenPaySuccess_screen_init(void);
extern lv_obj_t * ui_ScreenPaySuccess;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_TextArea12;
extern lv_obj_t * ui_Label43;
void ui_event_TextArea13(lv_event_t * e);
extern lv_obj_t * ui_TextArea13;
// SCREEN: ui_sign_up
void ui_sign_up_screen_init(void);
extern lv_obj_t * ui_sign_up;
void ui_event_usrname2(lv_event_t * e);
extern lv_obj_t * ui_usrname2;
void ui_event_usrname3(lv_event_t * e);
extern lv_obj_t * ui_usrname3;
extern lv_obj_t * ui_Keyboard2;
void ui_event_returnlogin(lv_event_t * e);
extern lv_obj_t * ui_returnlogin;
extern lv_obj_t * ui_Label33;
void ui_event_returnlogin2(lv_event_t * e);
extern lv_obj_t * ui_returnlogin2;
extern lv_obj_t * ui_Label44;
// SCREEN: ui_historylist
void ui_historylist_screen_init(void);
extern lv_obj_t * ui_historylist;
extern lv_obj_t * ui_list;
extern lv_obj_t * ui_templateitem2;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_num2;
extern lv_obj_t * ui_total;
extern lv_obj_t * ui_digtal;
void ui_event_returnscreencart(lv_event_t * e);
extern lv_obj_t * ui_returnscreencart;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_1062747148);    // assets/屏幕截图 2026-07-29 201000.png
LV_IMG_DECLARE(ui_img_435601465);    // assets/屏幕截图 2026-07-29 202752.png
LV_IMG_DECLARE(ui_img_qzs_png);    // assets/qzs.png
LV_IMG_DECLARE(ui_img_zt_png);    // assets/zt.png
LV_IMG_DECLARE(ui_img_cgz_png);    // assets/cgz.png
LV_IMG_DECLARE(ui_img_kz_png);    // assets/kz.png
LV_IMG_DECLARE(ui_img_shj_png);    // assets/shj.png
LV_IMG_DECLARE(ui_img_ccs_png);    // assets/ccs.png
LV_IMG_DECLARE(ui_img_yd_png);    // assets/yd.png
LV_IMG_DECLARE(ui_img_nm_png);    // assets/nm.png
LV_IMG_DECLARE(ui_img_sb_png);    // assets/sb.png
LV_IMG_DECLARE(ui_img_kl_png);    // assets/kl.png
LV_IMG_DECLARE(ui_img_ewm_png);    // assets/ewm.png



LV_FONT_DECLARE(ui_font_chinese162);
LV_FONT_DECLARE(ui_font_chinese163);
LV_FONT_DECLARE(ui_font_chinese20);
LV_FONT_DECLARE(ui_font_chinese30);
LV_FONT_DECLARE(ui_font_chinese36);
LV_FONT_DECLARE(ui_font_chinse16);
LV_FONT_DECLARE(ui_font_fansong16);
LV_FONT_DECLARE(ui_font_fansong30);
LV_FONT_DECLARE(ui_font_fansong301);
LV_FONT_DECLARE(ui_font_heiti30);
LV_FONT_DECLARE(ui_font_heiti301);
LV_FONT_DECLARE(ui_font_heiti36);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
