// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void btngotomain(lv_event_t * e);
void btn_sprite_cb(lv_event_t * e);
void btn_coke_cb(lv_event_t * e);
void btn_lemon_tea_cb(lv_event_t * e);
void btn_sport_drink_cb(lv_event_t * e);
void btn_crunchshark_cb(lv_event_t * e);
void btn_kissburn_cb(lv_event_t * e);
void btn_pillow_cb(lv_event_t * e);
void btn_mask_cb(lv_event_t * e);
void btn_haojia_cb(lv_event_t * e);
void btn_paper_cb(lv_event_t * e);
void btngotocheckout(lv_event_t * e);
void returnusrlogin(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
